### ISSUE TITLE
Mensa PDF conflitti

### ISSUE THREAD

**Issue by Helias** [UNICT-DMI/Telegram-ERSU-Bot#7]
- dopo che il file menu.pdf viene scaricato il bot lancia un errore, come se non aspettasse lo scaricamento del file ma provasse subito ad aprire il file

- il file PDF della mensa lo deve scaricare solo quando il file PDF disponibile comprende il giorno in cui si sta scaricando, se no così c'è il rischio che avendo già un file menu.pdf per il giorno corrente, lo scraper scarica il nuovo file PDF sovrascrivendo quello precedente

"se la data all'interno del PDF prevede il giorno corrente" si può controllare mediante il codice che estrae i dati dal PDF stesso

Suggerisco di salvare il file come **mensa_tmp.pdf** e poi eventualmente rinominarlo in mensa.pdf (**cancellando quello di prima)** nel caso in cui mensa_tmp.pdf comprende il menu della data corrente

**Comment by Pierpaolo791** [comment]
fatto, ma sarebbe meglio revisionare il codice e migliorarlo.
